"""Install and render the Codex PATH shim."""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import sys
from pathlib import Path


def default_state_dir() -> Path:
    """Return the user state directory for codex-speed."""

    return Path.home() / ".codex-speed"


def default_shim_dir() -> Path:
    """Return the directory that should be prepended to PATH."""

    return default_state_dir() / "bin"


def default_log_path() -> Path:
    """Return the daemon log path used by auto-start."""

    return default_state_dir() / "codex-speed-daemon.log"


def package_source_root() -> Path:
    """Return the import root for this checkout or installation."""

    return Path(__file__).resolve().parents[1]


def find_real_codex(shim_dir: Path | None = None) -> str | None:
    """Find a Codex executable on PATH, skipping the codex-speed shim."""

    shim_path = (shim_dir or default_shim_dir()) / "codex"
    env_real = os.environ.get("CODEX_SPEED_REAL_CODEX")
    if env_real:
        return env_real
    for entry in os.environ.get("PATH", "").split(os.pathsep):
        if not entry:
            continue
        candidate = Path(entry).expanduser() / "codex"
        try:
            if candidate.resolve() == shim_path.resolve():
                continue
        except OSError:
            continue
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate)
    found = shutil.which("codex")
    if found:
        try:
            if Path(found).resolve() == shim_path.resolve():
                return None
        except OSError:
            return None
    return found


def render_shim(real_codex: str, source_root: Path, python_bin: str) -> str:
    """Render the POSIX shell shim script."""

    source_root_text = str(source_root)
    package_dir_text = str(source_root / "codex_speed")
    return "\n".join(
        [
            "#!/bin/sh",
            "# Generated by codex-speed install-shim.",
            f"CODEX_SPEED_REAL_CODEX={shlex.quote(real_codex)}",
            "export CODEX_SPEED_REAL_CODEX",
            'case "${CODEX_SPEED_DISABLE:-}" in',
            '  ""|0|false|FALSE|no|NO) ;;',
            '  *) exec "$CODEX_SPEED_REAL_CODEX" "$@" ;;',
            "esac",
            f"if [ -d {shlex.quote(package_dir_text)} ]; then",
            '  if [ -n "${PYTHONPATH:-}" ]; then',
            f"    PYTHONPATH={shlex.quote(source_root_text)}:$PYTHONPATH",
            "  else",
            f"    PYTHONPATH={shlex.quote(source_root_text)}",
            "  fi",
            "  export PYTHONPATH",
            "fi",
            f"exec {shlex.quote(python_bin)} -m codex_speed auto -- \"$@\"",
            "",
        ]
    )


def install_shim(
    *,
    real_codex: str | None = None,
    shim_dir: Path | None = None,
    source_root: Path | None = None,
    python_bin: str | None = None,
) -> Path:
    """Install the Codex shim and return its path."""

    target_dir = shim_dir or default_shim_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    resolved_real = real_codex or find_real_codex(target_dir)
    if not resolved_real:
        raise FileNotFoundError("could not find the real codex executable on PATH")
    shim_path = target_dir / "codex"
    try:
        if Path(resolved_real).resolve() == shim_path.resolve():
            raise ValueError("real Codex executable resolves to the shim path")
    except OSError as exc:
        raise ValueError(f"real Codex executable is not usable: {resolved_real}") from exc
    root = source_root or package_source_root()
    interpreter = python_bin or sys.executable
    shim_path.write_text(render_shim(resolved_real, root, interpreter), encoding="utf-8")
    mode = shim_path.stat().st_mode
    shim_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return shim_path


def uninstall_shim(*, shim_dir: Path | None = None) -> bool:
    """Remove the codex-speed shim if it exists."""

    shim_path = (shim_dir or default_shim_dir()) / "codex"
    if not shim_path.exists():
        return False
    shim_path.unlink()
    return True
